title: Ramulator+DRAM Bender Tutorial @ ASPLOS 2026
description: Cutting-Edge Infrastructures for Real and Future Memory System Evaluation @ ASPLOS 2026
baseurl: ""
url: "https://olgunataberk.github.io/mccsys-asplos26"

# Theme settings
# remote_theme: pages-themes/primer@v0.6.0
theme: minima
plugins:
  - jekyll-remote-theme

# Site settings
show_downloads: false
google_analytics:

# Tutorial details
workshop:
  title: "Ramulator+DRAM Bender Tutorial"
  full_title: "Cutting-Edge Infrastructures for Real and Future Memory System Evaluation"
  date: "March 22nd, 2026"
  location: "Pittsburgh, USA"
  venue: "The Landing Hotel, 757 Casino Dr. Pittsburgh, PA 15212, Pittsburgh"
  conference: "ASPLOS 2026"
  conference_full: "ACM International Conference on Architectural Support for Programming Languages and Operating Systems"
  livestream: "TBD"
